### ISSUE TITLE
Deze app is gecrashed

### ISSUE THREAD

**Issue by Jovink** [athombv/com.danalock#3]
Version 1.0.1
Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/drivers/danalock_v2/driver.js:4:21)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: 1
Exit signal: null

**Comment by mruiter** [comment]
Did you install by appstore or github ?

I guess by github, then you have to put the zwave driver in the node_modules dir
Els nie worky nie
